appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J//aEUzJKi0x/zp4D6mW/2STsvlSUwmPkpuIVqkOwIg7ua8dfiaISCum65uaZ/HYQtcuF9fis99d/r52Ofc/MnfRCDw7avRWyLXj5d6T4wtY0en/7WTTOIkZCSiHKG8LnKS3A7tX2kmoeysIXlonW+VLN4ogS7T6r9cKDKfTKhT1uk13UjojEoFr01CtUDXw/6co3ZM7apC03jzcieKyIXEN8R1x2cmG5gIpXElywU1Q5Hd0LDB3PVsj+nNsCHPbzTu7QkHLl3XqQlAQD/r+GKjMpJC1LlYUkWpsqU+k0jvO1ZzyHi1X646dVCB8bbid9eWIzVOhIgt8EeDRIuXFYVVJShZjW1XU3VtfRB5eib+3VxcdoTLmQuOo6/38N1+/mnnFguCddmttqnaEnJbLs8lJJuvYCTSXgjsgxAkL0R8FeDnw4nWSXk0gBjwq3b6LUzyUqzCrBFSipeBuqmgdMW7MkQLR/wkAW2Sd69OIwWWIV7/lPkLQfEWCsQVI1KS1OdmHNvQz5mnxLbxlkXCzN0jpdg/2FmVUJTIgEq3wIROeVnXwoZRZ3bt7A1opJZ529bXVKRIx3Aypd7zJAG9lc2r4Ow2QVqXL3/xfVF+Qk9m80MDXqhMe6+BtERuPF9O4RdE173rECg7x41a7fM5zyQBeDPr7g/AA5xq2M4vAwUY=}
bot:
  automerge: true
